apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabriella-python-app
  namespace: grupp5
  labels:
    argocd.argoproj.io/instance: gabriella-python-app
spec:
  project: default
  source:
    repoURL: https://github.com/gabriellaohrn/gabriellas-python-app.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: grupp5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
